networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  # Сервис для PostgreSQL
  postgres:
    image: postgres:latest  # Используем официальный образ PostgreSQL
    container_name: postgres_db  # Имя контейнера
    environment:
      POSTGRES_USER: postgres      # Имя пользователя
      POSTGRES_PASSWORD: password  # Пароль пользователя
      POSTGRES_DB: postgres    # Имя базы данных
    ports:
      - "5432:5432"  # Пробрасываем порт 5432 на хост
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev  # Подключаем контейнер к сети
    

  backend:
    build:
      context: ./server
    networks:
      - dev
    depends_on:
      - postgres

  frontend:
    build:
      context: ./react-intro
    networks:
      - dev